name: MLflow CI

on:
  push:
    branches: ["main"]

permissions:
  contents: read

# env:
#   # Tracking MLflow konsisten di semua step
#   MLFLOW_TRACKING_URI: file:${{ github.workspace }}/MLProject/mlruns

env:
  MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/${{ secrets.DAGSHUB_REPO }}.mlflow
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}


jobs:
  train-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MLProject/requirements.txt

      - name: Run MLflow training & capture run_id
        run: |
          cd MLProject
          OUTPUT=$(mlflow run . --env-manager=local)
          echo "$OUTPUT"

      - name: Get latest run_id from DAGsHub
        run: |
          python - << 'EOF'
          import os
          from mlflow.tracking import MlflowClient

          EXPERIMENT_NAME = "bandung-house-price"

          client = MlflowClient()
          exp = client.get_experiment_by_name(EXPERIMENT_NAME)

          if exp is None:
              raise RuntimeError(f"Experiment '{EXPERIMENT_NAME}' not found")

          runs = client.search_runs(
              experiment_ids=[exp.experiment_id],
              order_by=["attributes.start_time DESC"],
              max_results=1,
          )

          if not runs:
              raise RuntimeError("No MLflow runs found")

          run_id = runs[0].info.run_id
          print("Captured RUN_ID:", run_id)

          with open(os.environ["GITHUB_ENV"], "a") as f:
              f.write(f"RUN_ID={run_id}\n")
          EOF



      - name: Verify RUN_ID
        run: |
          echo "RUN_ID is: '$RUN_ID'"
          if [ -z "$RUN_ID" ]; then
            echo "RUN_ID is empty, failing pipeline"
            exit 1
          fi

      - name: Build Docker image from MLflow model
        run: |
          mlflow models build-docker \
            --model-uri "runs:/$RUN_ID/model" \
            --name bandung-house-price

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker image
        run: |
          docker tag bandung-house-price \
            ${{ secrets.DOCKER_HUB_USERNAME }}/bandung-house-price:${RUN_ID}
          docker tag bandung-house-price \
            ${{ secrets.DOCKER_HUB_USERNAME }}/bandung-house-price:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/bandung-house-price:${RUN_ID}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/bandung-house-price:latest
