name: MLflow CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write


jobs:
  train-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MLProject/requirements.txt

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      - name: Save mlruns to repo
        run: |
          cd MLProject
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add mlruns/
          git commit -m "Save mlruns from CI run" || echo "No changes"
          git push
      
      - name: Get latest run_id
        run: |
          MODEL_PATH=$(ls -td mlruns/0/models/* | head -n 1)
          echo "MODEL_PATH=$MODEL_PATH" >> $GITHUB_ENV
          echo "Latest run_id: $MODEL_PATH"

      - name: Build Docker image from MLflow model
        run: |
          mlflow models build-docker \
            --model-uri "runs:/$MODEL_PATH/artifacts" \
            --name bandung-house-price

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker image
        run: |
          docker tag bandung-house-price \
          ${{ secrets.DOCKER_HUB_USERNAME }}/bandung-house-price:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/bandung-house-price:latest
